# Render Blueprint - Intento Simplificado

services:
  # Node.js Backend Service
  - type: web
    name: node-backend-market
    env: node
    # plan: free # Opcional, Render suele usar free por defecto
    rootDir: ./backend
    buildCommand: npm install
    startCommand: npm start
    # healthCheckPath: / # Eliminado temporalmente
    envVars:
      # DATABASE_URL será inyectada automáticamente
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      # - key: FRONTEND_URL # Añadir después si funciona
      #   value: https://tu-app.netlify.app

  # PostgreSQL Database Service
  - type: pserv
    name: postgres-db-market
    # plan: free # Eliminado temporalmente
