services:
  - type: web
    name: favoritosmarket-api
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: favoritosmarket-db
          property: connectionString

databases:
  - name: favoritosmarket-db
    plan: free
